name: Rust CI

on:
  push:
    branches: [main]
    paths:
      - 'contracts/**'
  pull_request:
    branches: [main]
    paths:
      - 'contracts/**'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy
      - run: rustup target add wasm32v1-none
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            contracts/Contract-V1
            contracts/Contract-V2
      - run: cargo build --target wasm32v1-none --release
        working-directory: contracts/Contract-V1
      - run: cargo fmt --all -- --check
        working-directory: contracts/Contract-V1
      - run: cargo fmt --all -- --check
        working-directory: contracts/Contract-V2
      - run: cargo clippy -- -D warnings
        working-directory: contracts/Contract-V1
      - run: cargo clippy -- -D warnings
        working-directory: contracts/Contract-V2
      - run: cargo test
        working-directory: contracts/Contract-V1
      - run: cargo test
        working-directory: contracts/Contract-V2
